### ISSUE TITLE
All the best

### ISSUE THREAD

**Issue by atZhengda** [wmira/fkit#1]
Hearing it's your last day in ANZ. Too bad wasn't able to say goodbye and thank you to you yet. 
All the best, Ninja!

**Comment by wmira** [comment]
hey Zhengda..was great working with you. i hope you enjoying react. Will
add you in LinkedIn.

Warren

On Aug 18, 2016 7:08 PM, "duz" notifications@github.com wrote:

Hearing it's your last day in ANZ. Too bad wasn't able to say goodbye and
thank you to you yet.
All the best, Ninja!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
https://github.com/wmira/fkit/issues/1, or mute the thread
